prices=(100,200,300,400,500)
total_bill=sum(prices)
print("total bill:",total_bill)
avg=total_bill/(len(prices))
print("average prices:",avg)
lowest_price=min(prices)
print("lowest price:",lowest_price)
highest_price=max(prices)
print("highest prices:",highest_price)